import { env } from "cloudflare:workers";
import { Form, useNavigation } from "react-router";
import type { Route } from "./+types/admin.orders";
import { requireSessionUser } from "../lib/auth.server";
import { nextDocumentNumber } from "../lib/documents.server";
import { canTransition, nextStates } from "../lib/workflow";
import { valueOf } from "../lib/validation";
import { writeAudit } from "../lib/audit.server";

type Order = { id: string; order_number: string; customer_name: string; customer_reference: string | null; quote_number: string | null; shipper_name: string; consignee_name: string; origin_country: string; origin_city: string; destination_country: string; destination_city: string; cargo_description: string; pieces: number; gross_weight_kg: number; volume_cbm: number; transport_mode: string; requested_pickup_date: string | null; requested_delivery_date: string | null; status: string; source: string; created_at: string };
type QuoteRef = { id: string; quote_number: string; customer_id: string; customer_name: string };

export async function loader({ request }: Route.LoaderArgs) {
  const current = await requireSessionUser(request, "order.view");
  const [orders, customers, quotes, countries, modes, services] = await Promise.all([
    env.DB.prepare(`SELECT o.id, o.order_number, c.name AS customer_name, o.customer_reference, q.quote_number, o.shipper_name, o.consignee_name, o.origin_country, o.origin_city, o.destination_country, o.destination_city, o.cargo_description, o.pieces, o.gross_weight_kg, o.volume_cbm, o.transport_mode, o.requested_pickup_date, o.requested_delivery_date, o.status, o.source, o.created_at FROM transport_orders o JOIN customers c ON c.id = o.customer_id LEFT JOIN quotations q ON q.id = o.quotation_id WHERE o.organization_id = ? ORDER BY o.created_at DESC LIMIT 250`).bind(current.organizationId).all<Order>(),
    env.DB.prepare("SELECT id, code, name FROM customers WHERE organization_id = ? AND status = 'active' ORDER BY name").bind(current.organizationId).all<{ id: string; code: string; name: string }>(),
    env.DB.prepare(`SELECT q.id, q.quote_number, q.customer_id, c.name AS customer_name FROM quotations q JOIN customers c ON c.id = q.customer_id WHERE q.organization_id = ? AND q.status = 'accepted' AND NOT EXISTS (SELECT 1 FROM transport_orders o WHERE o.quotation_id = q.id) ORDER BY q.accepted_at DESC`).bind(current.organizationId).all<QuoteRef>(),
    ref(current.organizationId, "country"), ref(current.organizationId, "transport_mode"), ref(current.organizationId, "service_level"),
  ]);
  return { current, orders: orders.results, customers: customers.results, quotes: quotes.results, countries: countries.results, modes: modes.results, services: services.results };
}

export async function action({ request }: Route.ActionArgs) {
  const current = await requireSessionUser(request, "order.manage");
  const form = await request.formData(), intent = valueOf(form, "intent"), now = new Date().toISOString();
  if (intent === "status") {
    const id = valueOf(form, "id"), status = valueOf(form, "status");
    const order = await env.DB.prepare("SELECT status FROM transport_orders WHERE id = ? AND organization_id = ?").bind(id, current.organizationId).first<{ status: string }>();
    if (!order || !canTransition("order", order.status, status)) return { formError: "订单状态流转无效" };
    await env.DB.prepare("UPDATE transport_orders SET status = ?, confirmed_at = CASE WHEN ? = 'confirmed' THEN ? ELSE confirmed_at END, updated_at = ? WHERE id = ? AND organization_id = ?").bind(status, status, now, now, id, current.organizationId).run();
    await writeAudit({ request, action: "order.status", resourceType: "transport_order", resourceId: id, organizationId: current.organizationId, actorUserId: current.userId, metadata: { from: order.status, to: status } });
    return { success: "订单状态已更新" };
  }
  const quotationId = valueOf(form, "quotationId"), formCustomerId = valueOf(form, "customerId"), reference = valueOf(form, "reference"), shipper = valueOf(form, "shipper"), shipperContact = valueOf(form, "shipperContact"), shipperPhone = valueOf(form, "shipperPhone"), originCountryForm = valueOf(form, "originCountry"), originCityForm = valueOf(form, "originCity"), originAddress = valueOf(form, "originAddress"), consignee = valueOf(form, "consignee"), consigneeContact = valueOf(form, "consigneeContact"), consigneePhone = valueOf(form, "consigneePhone"), destinationCountryForm = valueOf(form, "destinationCountry"), destinationCityForm = valueOf(form, "destinationCity"), destinationAddress = valueOf(form, "destinationAddress"), cargoForm = valueOf(form, "cargo"), modeForm = valueOf(form, "mode"), serviceForm = valueOf(form, "service"), pickupDate = valueOf(form, "pickupDate"), deliveryDate = valueOf(form, "deliveryDate"), instructions = valueOf(form, "instructions");
  const piecesForm = Number(valueOf(form, "pieces") || 1), weightForm = Number(valueOf(form, "weight") || 0), volumeForm = Number(valueOf(form, "volume") || 0);
  const quote = quotationId ? await env.DB.prepare("SELECT customer_id, origin_country, origin_city, destination_country, destination_city, cargo_description, pieces, gross_weight_kg, volume_cbm, transport_mode, service_level FROM quotations WHERE id = ? AND organization_id = ? AND status = 'accepted'").bind(quotationId, current.organizationId).first<Record<string, string | number>>() : null;
  const customerId = String(quote?.customer_id ?? formCustomerId), originCountry = String(quote?.origin_country ?? originCountryForm), originCity = String(quote?.origin_city ?? originCityForm), destinationCountry = String(quote?.destination_country ?? destinationCountryForm), destinationCity = String(quote?.destination_city ?? destinationCityForm), cargo = String(quote?.cargo_description ?? cargoForm), mode = String(quote?.transport_mode ?? modeForm), service = String(quote?.service_level ?? serviceForm), pieces = Number(quote?.pieces ?? piecesForm), weight = Number(quote?.gross_weight_kg ?? weightForm), volume = Number(quote?.volume_cbm ?? volumeForm);
  if (!(await env.DB.prepare("SELECT 1 FROM customers WHERE id = ? AND organization_id = ? AND status = 'active'").bind(customerId, current.organizationId).first())) return { formError: "客户无效" };
  if (quotationId && !quote) return { formError: "报价无效或尚未接受" };
  if (![shipper, originCity, originAddress, consignee, destinationCity, destinationAddress, cargo, mode].every(Boolean) || !Number.isInteger(pieces) || pieces < 1 || weight < 0 || volume < 0) return { formError: "请填写完整收发货、货物和路线信息" };
  const id = crypto.randomUUID(), number = await nextDocumentNumber(current.organizationId, "order");
  await env.DB.prepare(`INSERT INTO transport_orders (id, organization_id, order_number, customer_id, quotation_id, customer_reference, shipper_name, shipper_contact, shipper_phone, origin_country, origin_city, origin_address, consignee_name, consignee_contact, consignee_phone, destination_country, destination_city, destination_address, cargo_description, pieces, gross_weight_kg, volume_cbm, transport_mode, service_level, requested_pickup_date, requested_delivery_date, source, special_instructions, created_by_user_id, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 'admin', ?, ?, ?, ?)`).bind(id, current.organizationId, number, customerId, quotationId || null, reference || null, shipper, shipperContact || null, shipperPhone || null, originCountry, originCity, originAddress, consignee, consigneeContact || null, consigneePhone || null, destinationCountry, destinationCity, destinationAddress, cargo, pieces, weight, volume, mode, service || null, pickupDate || null, deliveryDate || null, instructions || null, current.userId, now, now).run();
  await writeAudit({ request, action: "order.create", resourceType: "transport_order", resourceId: id, organizationId: current.organizationId, actorUserId: current.userId, metadata: { number, source: "admin" } });
  return { success: `订单 ${number} 已创建` };
}

function ref(org: string, category: string) { return env.DB.prepare("SELECT code, name FROM reference_data WHERE organization_id = ? AND category = ? AND status = 'active' ORDER BY sort_order").bind(org, category).all<{ code: string; name: string }>(); }
export function meta() { return [{ title: "运输订单 | International TMS" }]; }
const labels: Record<string, string> = { draft: "草稿", submitted: "待确认", confirmed: "已确认", in_execution: "执行中", completed: "已完成", cancelled: "已取消" };

export default function Orders({ loaderData, actionData }: Route.ComponentProps) {
  const busy = useNavigation().state !== "idle", manage = loaderData.current.permissions.includes("order.manage");
  return <><header className="page-header"><div><p className="eyebrow">TRANSPORT ORDER</p><h1>运输订单</h1><p>承接报价或直接创建客户运输委托。</p></div><span className="status-pill">{loaderData.orders.length} 票订单</span></header>{(actionData?.success || actionData?.formError) && <div className={`alert ${actionData.formError ? "error" : "success"}`}>{actionData.formError ?? actionData.success}</div>}
    {manage && <details className="panel expandable" open={loaderData.orders.length === 0}><summary>创建运输订单</summary><Form method="post" className="form-grid"><input type="hidden" name="intent" value="create"/><Sel label="已接受报价" name="quotationId" optional items={loaderData.quotes.map(q => [q.id, `${q.quote_number} · ${q.customer_name}`])}/><Sel label="客户（无报价时）" name="customerId" optional items={loaderData.customers.map(c => [c.id, `${c.code} · ${c.name}`])}/><label className="field"><span>客户参考号</span><input name="reference"/></label><label className="field"><span>要求提货日</span><input name="pickupDate" type="date"/></label><label className="field"><span>发货人</span><input name="shipper" required/></label><label className="field"><span>发货联系人/电话</span><input name="shipperContact" placeholder="联系人"/><input name="shipperPhone" placeholder="电话"/></label><Sel label="起运国家" name="originCountry" optional items={loaderData.countries.map(i => [i.code, i.name])}/><label className="field"><span>起运城市</span><input name="originCity"/></label><label className="field span-2"><span>提货地址</span><input name="originAddress" required/></label><label className="field"><span>收货人</span><input name="consignee" required/></label><label className="field"><span>收货联系人/电话</span><input name="consigneeContact" placeholder="联系人"/><input name="consigneePhone" placeholder="电话"/></label><Sel label="目的国家" name="destinationCountry" optional items={loaderData.countries.map(i => [i.code, i.name])}/><label className="field"><span>目的城市</span><input name="destinationCity"/></label><label className="field span-2"><span>送货地址</span><input name="destinationAddress" required/></label><label className="field span-2"><span>货物描述</span><input name="cargo"/></label><Num name="pieces" label="件数" value="1"/><Num name="weight" label="毛重（KG）"/><Num name="volume" label="体积（CBM）" step="0.001"/><Sel label="运输方式" name="mode" optional items={loaderData.modes.map(i => [i.code, i.name])}/><Sel label="服务等级" name="service" optional items={loaderData.services.map(i => [i.code, i.name])}/><label className="field"><span>要求送达日</span><input name="deliveryDate" type="date"/></label><label className="field span-2"><span>特殊要求</span><input name="instructions"/></label><button className="primary" disabled={busy}>创建订单</button></Form></details>}
    <section className="panel"><div className="table-wrap"><table><thead><tr><th>订单/客户</th><th>收发货</th><th>货物</th><th>计划</th><th>来源</th><th>状态</th></tr></thead><tbody>{loaderData.orders.map(o => <tr key={o.id}><td><strong>{o.order_number}</strong><small>{o.customer_name}{o.quote_number ? ` · ${o.quote_number}` : ""}</small></td><td><strong>{o.origin_country} {o.origin_city} → {o.destination_country} {o.destination_city}</strong><small>{o.shipper_name} → {o.consignee_name}</small></td><td><strong>{o.cargo_description}</strong><small>{o.pieces} 件 · {o.gross_weight_kg} KG · {o.volume_cbm} CBM</small></td><td><strong>{o.requested_pickup_date || "待定"}</strong><small>送达 {o.requested_delivery_date || "待定"}</small></td><td>{o.source === "portal" ? "客户门户" : "后台"}</td><td>{manage && nextStates("order", o.status).length ? <Form method="post" className="inline-form"><input type="hidden" name="intent" value="status"/><input type="hidden" name="id" value={o.id}/><select name="status" defaultValue=""><option value="" disabled>{labels[o.status]}</option>{nextStates("order", o.status).map(s => <option key={s} value={s}>{labels[s]}</option>)}</select><button className="text-button">更新</button></Form> : <span className="status-pill">{labels[o.status]}</span>}</td></tr>)}</tbody></table></div></section>
  </>;
}
function Sel({ label, name, items, optional }: { label: string; name: string; items: [string,string][]; optional?: boolean }) { return <label className="field"><span>{label}</span><select name={name} required={!optional}><option value="">{optional ? "未指定" : "请选择"}</option>{items.map(([v,t]) => <option key={v} value={v}>{t}</option>)}</select></label>; }
function Num({ label, name, value="0", step="1" }: { label:string; name:string; value?:string; step?:string }) { return <label className="field"><span>{label}</span><input name={name} type="number" min="0" step={step} defaultValue={value}/></label>; }
