import { env } from "cloudflare:workers";
import { Form, useNavigation } from "react-router";
import type { Route } from "./+types/portal.orders";
import { requirePortalCustomer } from "../lib/portal.server";
import { nextDocumentNumber } from "../lib/documents.server";
import { canTransition } from "../lib/workflow";
import { valueOf } from "../lib/validation";
import { writeAudit } from "../lib/audit.server";

type Order={id:string;order_number:string;customer_reference:string|null;shipper_name:string;consignee_name:string;origin_country:string;origin_city:string;destination_country:string;destination_city:string;cargo_description:string;pieces:number;gross_weight_kg:number;volume_cbm:number;requested_pickup_date:string|null;requested_delivery_date:string|null;status:string;created_at:string};
type Quote={id:string;quote_number:string;origin_city:string;destination_city:string;cargo_description:string;currency:string;total_amount:number;valid_until:string|null;status:string};

export async function loader({request}:Route.LoaderArgs){
  const {user,customer}=await requirePortalCustomer(request);
  const [orders,quotes,countries,modes,services]=await Promise.all([
    env.DB.prepare("SELECT id,order_number,customer_reference,shipper_name,consignee_name,origin_country,origin_city,destination_country,destination_city,cargo_description,pieces,gross_weight_kg,volume_cbm,requested_pickup_date,requested_delivery_date,status,created_at FROM transport_orders WHERE organization_id=? AND customer_id=? ORDER BY created_at DESC").bind(user.organizationId,customer.id).all<Order>(),
    env.DB.prepare("SELECT id,quote_number,origin_city,destination_city,cargo_description,currency,total_amount,valid_until,status FROM quotations WHERE organization_id=? AND customer_id=? AND status IN ('sent','accepted','rejected') ORDER BY created_at DESC").bind(user.organizationId,customer.id).all<Quote>(),
    ref(user.organizationId,"country"),ref(user.organizationId,"transport_mode"),ref(user.organizationId,"service_level"),
  ]);
  return {user,customer,orders:orders.results,quotes:quotes.results,countries:countries.results,modes:modes.results,services:services.results};
}

export async function action({request}:Route.ActionArgs){
  const {user,customer}=await requirePortalCustomer(request),form=await request.formData(),intent=valueOf(form,"intent"),now=new Date().toISOString();
  if(intent==="quote"){
    const id=valueOf(form,"id"),status=valueOf(form,"status");
    const quote=await env.DB.prepare("SELECT status FROM quotations WHERE id=? AND organization_id=? AND customer_id=?").bind(id,user.organizationId,customer.id).first<{status:string}>();
    if(!quote||!canTransition("quote",quote.status,status)||!["accepted","rejected"].includes(status))return {formError:"报价状态操作无效"};
    await env.DB.prepare("UPDATE quotations SET status=?,accepted_at=CASE WHEN ?='accepted' THEN ? ELSE accepted_at END,updated_at=? WHERE id=? AND organization_id=? AND customer_id=?").bind(status,status,now,now,id,user.organizationId,customer.id).run();
    await writeAudit({request,action:"portal.quote.response",resourceType:"quotation",resourceId:id,organizationId:user.organizationId,actorUserId:user.userId,metadata:{status}});
    return {success:status==="accepted"?"报价已接受，可联系客户经理转正式订单":"报价已拒绝"};
  }
  const reference=valueOf(form,"reference"),shipper=valueOf(form,"shipper"),shipperContact=valueOf(form,"shipperContact"),shipperPhone=valueOf(form,"shipperPhone"),originCountry=valueOf(form,"originCountry"),originCity=valueOf(form,"originCity"),originAddress=valueOf(form,"originAddress"),consignee=valueOf(form,"consignee"),consigneeContact=valueOf(form,"consigneeContact"),consigneePhone=valueOf(form,"consigneePhone"),destinationCountry=valueOf(form,"destinationCountry"),destinationCity=valueOf(form,"destinationCity"),destinationAddress=valueOf(form,"destinationAddress"),cargo=valueOf(form,"cargo"),mode=valueOf(form,"mode"),service=valueOf(form,"service"),pickup=valueOf(form,"pickupDate"),delivery=valueOf(form,"deliveryDate"),instructions=valueOf(form,"instructions");
  const pieces=Number(valueOf(form,"pieces")||1),weight=Number(valueOf(form,"weight")||0),volume=Number(valueOf(form,"volume")||0);
  if(![shipper,originCountry,originCity,originAddress,consignee,destinationCountry,destinationCity,destinationAddress,cargo,mode].every(Boolean)||!Number.isInteger(pieces)||pieces<1||weight<0||volume<0)return {formError:"请填写完整收发货、货物和路线信息"};
  const id=crypto.randomUUID(),number=await nextDocumentNumber(user.organizationId,"order");
  await env.DB.prepare(`INSERT INTO transport_orders(id,organization_id,order_number,customer_id,customer_reference,shipper_name,shipper_contact,shipper_phone,origin_country,origin_city,origin_address,consignee_name,consignee_contact,consignee_phone,destination_country,destination_city,destination_address,cargo_description,pieces,gross_weight_kg,volume_cbm,transport_mode,service_level,requested_pickup_date,requested_delivery_date,status,source,special_instructions,created_by_user_id,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,'submitted','portal',?,?,?,?)`).bind(id,user.organizationId,number,customer.id,reference||null,shipper,shipperContact||null,shipperPhone||null,originCountry,originCity,originAddress,consignee,consigneeContact||null,consigneePhone||null,destinationCountry,destinationCity,destinationAddress,cargo,pieces,weight,volume,mode,service||null,pickup||null,delivery||null,instructions||null,user.userId,now,now).run();
  await writeAudit({request,action:"portal.order.submit",resourceType:"transport_order",resourceId:id,organizationId:user.organizationId,actorUserId:user.userId,metadata:{number}});
  return {success:`运输需求 ${number} 已提交，等待欧凌确认`};
}
function ref(org:string,category:string){return env.DB.prepare("SELECT code,name FROM reference_data WHERE organization_id=? AND category=? AND status='active' ORDER BY sort_order").bind(org,category).all<{code:string;name:string}>()}
export function meta(){return[{title:"我的订单 | 欧凌客户门户"}]}
const orderLabels:Record<string,string>={draft:"草稿",submitted:"待确认",confirmed:"已确认",in_execution:"执行中",completed:"已完成",cancelled:"已取消"};
const quoteLabels:Record<string,string>={sent:"待确认",accepted:"已接受",rejected:"已拒绝"};
export default function PortalOrders({loaderData,actionData}:Route.ComponentProps){const busy=useNavigation().state!=="idle";return <><header className="page-header"><div><p className="eyebrow">BOOKING</p><h1>报价与订单</h1><p>在线确认报价、提交运输需求并查看处理状态。</p></div></header>{(actionData?.success||actionData?.formError)&&<div className={`alert ${actionData.formError?"error":"success"}`}>{actionData.formError??actionData.success}</div>}
  {loaderData.quotes.length>0&&<section className="panel"><h2>待确认报价</h2><div className="table-wrap"><table><thead><tr><th>报价号</th><th>路线/货物</th><th>金额</th><th>有效期</th><th>状态</th></tr></thead><tbody>{loaderData.quotes.map(q=><tr key={q.id}><td>{q.quote_number}</td><td><strong>{q.origin_city} → {q.destination_city}</strong><small>{q.cargo_description}</small></td><td>{q.currency} {q.total_amount.toLocaleString()}</td><td>{q.valid_until||"—"}</td><td>{q.status==="sent"?<div className="button-row"><Form method="post"><input type="hidden" name="intent" value="quote"/><input type="hidden" name="id" value={q.id}/><input type="hidden" name="status" value="accepted"/><button className="text-button">接受</button></Form><Form method="post"><input type="hidden" name="intent" value="quote"/><input type="hidden" name="id" value={q.id}/><input type="hidden" name="status" value="rejected"/><button className="text-button danger">拒绝</button></Form></div>:<span className="status-pill">{quoteLabels[q.status]}</span>}</td></tr>)}</tbody></table></div></section>}
  <details className="panel expandable" open={loaderData.orders.length===0}><summary>提交运输需求</summary><Form method="post" className="form-grid"><input type="hidden" name="intent" value="order"/><label className="field"><span>客户参考号</span><input name="reference"/></label><label className="field"><span>要求提货日</span><input name="pickupDate" type="date"/></label><label className="field"><span>发货人</span><input name="shipper" required/></label><label className="field"><span>发货联系人/电话</span><input name="shipperContact"/><input name="shipperPhone"/></label><Sel label="起运国家" name="originCountry" items={loaderData.countries.map(i=>[i.code,i.name])}/><label className="field"><span>起运城市</span><input name="originCity" required/></label><label className="field span-2"><span>提货地址</span><input name="originAddress" required/></label><label className="field"><span>收货人</span><input name="consignee" required/></label><label className="field"><span>收货联系人/电话</span><input name="consigneeContact"/><input name="consigneePhone"/></label><Sel label="目的国家" name="destinationCountry" items={loaderData.countries.map(i=>[i.code,i.name])}/><label className="field"><span>目的城市</span><input name="destinationCity" required/></label><label className="field span-2"><span>送货地址</span><input name="destinationAddress" required/></label><label className="field span-2"><span>货物描述</span><input name="cargo" required/></label><Num label="件数" name="pieces" value="1"/><Num label="毛重（KG）" name="weight"/><Num label="体积（CBM）" name="volume" step="0.001"/><Sel label="运输方式" name="mode" items={loaderData.modes.map(i=>[i.code,i.name])}/><Sel label="服务等级" name="service" optional items={loaderData.services.map(i=>[i.code,i.name])}/><label className="field"><span>要求送达日</span><input name="deliveryDate" type="date"/></label><label className="field span-2"><span>特殊要求</span><input name="instructions"/></label><button className="primary portal-primary" disabled={busy}>提交运输需求</button></Form></details>
  <section className="panel"><h2>我的订单</h2><div className="table-wrap"><table><thead><tr><th>订单号</th><th>路线</th><th>货物</th><th>计划</th><th>状态</th></tr></thead><tbody>{loaderData.orders.map(o=><tr key={o.id}><td><strong>{o.order_number}</strong><small>{o.customer_reference||"—"}</small></td><td>{o.origin_country} {o.origin_city} → {o.destination_country} {o.destination_city}</td><td><strong>{o.cargo_description}</strong><small>{o.pieces} 件 · {o.gross_weight_kg} KG · {o.volume_cbm} CBM</small></td><td>{o.requested_pickup_date||"待定"} → {o.requested_delivery_date||"待定"}</td><td><span className="status-pill">{orderLabels[o.status]}</span></td></tr>)}</tbody></table></div></section></>}
function Sel({label,name,items,optional}:{label:string;name:string;items:[string,string][];optional?:boolean}){return <label className="field"><span>{label}</span><select name={name} required={!optional}><option value="">{optional?"未指定":"请选择"}</option>{items.map(([v,t])=><option key={v} value={v}>{t}</option>)}</select></label>}
function Num({label,name,value="0",step="1"}:{label:string;name:string;value?:string;step?:string}){return <label className="field"><span>{label}</span><input name={name} type="number" min="0" step={step} defaultValue={value}/></label>}
