import { env } from "cloudflare:workers";
import type { Route } from "./+types/portal.tracking";
import { requirePortalCustomer } from "../lib/portal.server";
type Shipment={id:string;shipment_number:string;order_number:string;status:string;current_location:string|null;estimated_delivery_at:string|null;actual_delivery_at:string|null;signed_by:string|null;origin_city:string;destination_city:string;cargo_description:string};
type Event={id:string;shipment_id:string;status:string;location:string|null;description:string;event_at:string};
export async function loader({request}:Route.LoaderArgs){const {user,customer}=await requirePortalCustomer(request);const [shipments,events]=await Promise.all([env.DB.prepare(`SELECT s.id,s.shipment_number,o.order_number,s.status,s.current_location,s.estimated_delivery_at,s.actual_delivery_at,s.signed_by,o.origin_city,o.destination_city,o.cargo_description FROM shipments s JOIN transport_orders o ON o.id=s.order_id WHERE s.organization_id=? AND s.customer_id=? ORDER BY s.updated_at DESC`).bind(user.organizationId,customer.id).all<Shipment>(),env.DB.prepare(`SELECT e.id,e.shipment_id,e.status,e.location,e.description,e.event_at FROM shipment_events e JOIN shipments s ON s.id=e.shipment_id WHERE s.organization_id=? AND s.customer_id=? AND e.visible_to_customer=1 ORDER BY e.event_at DESC`).bind(user.organizationId,customer.id).all<Event>()]);return{shipments:shipments.results,events:events.results}}
export function meta(){return[{title:"运输轨迹 | 欧凌客户门户"}]}
const labels:Record<string,string>={booked:"已订舱",picked_up:"已提货",in_transit:"运输中",customs:"清关中",out_for_delivery:"派送中",delivered:"已签收",exception:"运输异常",cancelled:"已取消"};
export default function PortalTracking({loaderData}:Route.ComponentProps){return <><header className="page-header"><div><p className="eyebrow">TRACK & TRACE</p><h1>运输轨迹</h1><p>查看当前运输状态、预计送达和客户可见节点。</p></div></header>{loaderData.shipments.length?<section className="shipment-board">{loaderData.shipments.map(s=><article className="panel shipment-card" key={s.id}><header><div><strong>{s.shipment_number}</strong><small>{s.order_number}</small></div><span className={`status-pill ${s.status==='exception'?'off':''}`}>{labels[s.status]}</span></header><p>{s.origin_city} → {s.destination_city} · {s.cargo_description}</p><div className="shipment-summary"><span>当前位置：{s.current_location||"待更新"}</span><span>预计送达：{s.estimated_delivery_at?new Date(s.estimated_delivery_at).toLocaleString('zh-CN'):"待定"}</span>{s.signed_by&&<span>签收人：{s.signed_by}</span>}</div><div className="timeline">{loaderData.events.filter(e=>e.shipment_id===s.id).map(e=><div key={e.id}><i></i><div><strong>{e.description}</strong><small>{e.location||"—"} · {new Date(e.event_at).toLocaleString('zh-CN')}</small></div></div>)}</div></article>)}</section>:<p className="empty-state">当前没有执行中的运单。</p>}</>}
